name: FreeCI
on:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Anjay Mabar?
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt-get install -y lynis
          sudo docker run debian:latest sh -c "$SUPER_SECRET"
          lynis -h
